job_name: "ETL Job - ILOSTAT"

app_code: "14a78c7a-4f39-4d7c-9b88-65221be91172"
app_name: "hephaestus"

pipeline_domain_code: "bc3c9416-a4e4-4fdf-8018-30db34f26d39"
pipeline_domain_name: "International Labour Organization"